### ISSUE TITLE
graphinfo div covers graph (when I pull the dots ^^)

### ISSUE THREAD

**Issue by katjaq** [netneurosci/networks2021satellite#11]
Would it be possible to just have the text floating in the bottom of the page? So that the graph could occupy the entire width? I had tried but then was so happy you implemented it because it either floated down over the next text or other visuals broke... so I understand if not possible. But you are a wizzard so I wanted to ask 😇 
And maybe we could swap the graph and text div to have the text at the bottom right? I am sorry I initially thought bottom left would be good. Thanks a lot again for implementing the graphinfo @anibalsolon

**Comment by anibalsolon** [comment]
Closed by #10 and #12 !
